service: slack-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  stage: dev
  timeout: 10
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/*"
            # 전체 테이블
plugins:
  - serverless-dynamodb
  - serverless-offline
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
layers:
  pyjwt:
    path: pyjwt
    description: pyjwt layer
    compatibleRuntimes:
      - python3.10
      - python3.9
    retain: true # layer versions are not deleted as new ones are created
functions:
  hello:
    handler: api/hello.hello
    events:
      - httpApi:
          path: /hello
          method: get
  create:
    handler: api/create.create
    events:
      - httpApi:
          path: /api
          method: post

  list:
    handler: api/list.list
    events:
      - httpApi:
          path: /api
          method: get

  get:
    handler: api/get.get
    events:
      - httpApi:
          path: /api/{id}
          method: get

  update:
    handler: api/update.update
    events:
      - httpApi:
          path: /api/{id}
          method: put

  delete:
    handler: api/delete.delete
    events:
      - httpApi:
          path: /api/{id}
          method: delete
  addUser:
    handler: api/add_user.add_user
    events:
      - httpApi:
          path: /user
          method: post
  addWorkspace:
    handler: api/workspace/add_workspace.add_workspace
    events:
      - httpApi:
          path: /workspace
          method: post
  addChannel:
    handler: api/add_channel.add_channel
    events:
      - httpApi:
          path: /channel
          method: post
resources:
  Resources:

    # table definition
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: todo-table-${sls:stage}

    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: user-table-${sls:stage}

    ChannelDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: channel_id
            AttributeType: S
        KeySchema:
          - AttributeName: channel_name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: channel-table-${sls:stage}

    WorkSpaceDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: workspace_id
            AttributeType: S
        KeySchema:
          - AttributeName: workspace_name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: workspace-table-${sls:stage}
    ChannelChattingDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: chat_id
            AttributeType: S
        KeySchema:
          - AttributeName: chat_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: channel-chatting-table-${sls:stage}

    DMDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: dm_id
            AttributeType: S
        KeySchema:
          - AttributeName: dm_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: dm-table-${sls:stage}

